---
apiVersion: v1
kind: Pod
metadata:
  name: claude-pod
  labels:
    app: gemini
  annotations:
    io.podman.annotations.userns: keep-id
    container.apparmor.security.beta.kubernetes.io/gemini: unconfined
    container.seccomp.security.alpha.kubernetes.io/gemini: unconfined
spec:
  containers:
    - name: gemini
      image: localhost/gemini:latest
      stdin: true
      tty: true
      volumeMounts:
        - name: workspace
          mountPath: /workspace:z
        - name: agent-data
          mountPath: /home/gemini/.gemini:z
        - name: agent-config
          mountPath: /home/gemini/.gemini.json:z
      env:
        - name: GEMINI_WORKSPACE
          value: /workspace
      securityContext:
        allowPrivilegeEscalation: false
        runAsUser: 1000
        runAsGroup: 1000
        seccompProfile:
          type: Unconfined
        capabilities:
          drop:
            - NET_RAW
      imagePullPolicy: Never

  volumes:
    - name: workspace
      hostPath:
        path: /workspace
        type: Directory
    - name: agent-data
      hostPath:
        path: ~/.local/share/agentonaut/gemini
        type: DirectoryOrCreate
    - name: agent-config
      hostPath:
        path: ~/.config/agentonaut/gemini/gemini.json
        type: FileOrCreate

  restartPolicy: Never
  dnsPolicy: ClusterFirst
  shareProcessNamespace: false
